### ISSUE TITLE
Search input fixed on top of the page

### ISSUE THREAD

**Issue by vincentrooy** [Orange-OpenSource/uuv#360]
Hi,

Could we make the current search bar sticky at the top of  [uuv docs](https://orange-opensource.github.io/uuv/docs/wordings/generated-wording-description/en-generated-wording-description#i-should-see-elements-of-the-list-with-name-string) pages. It would stay in view when scrolling, enhancing usability.
`#search-bar {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 10;
}`

Best,

**Comment by vr-varad** [comment]
@stanlee974 I would like to work on these if its open for contribution

**Comment by stanlee974** [comment]
Hi ! @vr-varad !

You can take it. Thank you very much for you effort. It give us power to continue

**Comment by vr-varad** [comment]
Sorry @stanlee974 isn't it already fixed I didn't get clearly what was asked because I think it's already implemented what is asked.https://github.com/user-attachments/assets/80918a1a-8876-4d5d-ae36-e7d23f698e16

**Comment by stanlee974** [comment]
Hi @vr-varad !

This issue concern this component ![Image](https://github.com/user-attachments/assets/106ba5c7-2329-4c72-9b25-db0d51cf8f78)
on this page : https://orange-opensource.github.io/uuv/docs/wordings/generated-wording-description/en-generated-wording-description.

When you scroll, the component disapeared.

**Comment by vr-varad** [comment]
OK!! Thanks a lot for confirmation
