### ISSUE TITLE
Not compatible with JetBrains WebStorm Build 233

### ISSUE THREAD

**Issue by yanikem** [Orange-OpenSource/uuv#399]
Please update your plugin to work with JetBrains WebStorm Build 233.

<img width="413" alt="Screenshot 2023-12-16 at 7 52 22 AM" src="https://github.com/Orange-OpenSource/uuv/assets/129122733/424f5bff-6f1a-4e2d-bae5-0cacfe02ae81">

**Comment by stanlee974** [comment]
Hi @yanikem, thank you for the issue. 
We checked configuration and the last version of the plugin is compatible from 222 to 232 included. 
Can you tell us which version of webstorm you're running?
Thank you for your reply ;-)

**Comment by yanikem** [comment]
WebStorm 2023.3.1
Build #WS-233.11799.293, built on December 11, 2023
Mac OS X

On Dec 17, 2023, at 11:52 AM, Stanley Servical ***@***.***> wrote:



Hi @yanikem<https://github.com/yanikem>, thank you for the issue.
We checked configuration and the last version of the plugin is compatible from 222 to 232 included.
Can you tell us which version of webstorm you're running?
Thank you for your reply ;-)

**Comment by stanlee974** [comment]
Hi @yanikem ! we make a patch on gradle configuration on the 1.2.2 version. Can you check if it's better? If not, we reopen the ticket.
Thank you for your time ;-)
