### ISSUE TITLE
Broken link in readme files

### ISSUE THREAD

**Issue by stanlee974** [Orange-OpenSource/uuv#553]
replace Rich dictionary link is broken in readme files: 
- README.md
- packages/assistant/README.md
- packages/runner-cypress/README.md
- packages/runner-playwright/README.md
by `https://orange-opensource.github.io/uuv/docs/category/step-definition`

@patrick-mota Thank you for your comment ;-)

**Comment by patrick-mota** [comment]
@stanlee974 You're welcome (and fast :D).

I just did a PR about this.

**Comment by stanlee974** [comment]
I Just squash the commit message because docs in parenthesis means that it only impacts the docs package, in our release management.
Thank you again 😏
