### ISSUE TITLE
(runner-playwright) Command test not found in 2.10.0

### ISSUE THREAD

**Issue by stanlee974** [Orange-OpenSource/uuv#564]
### the output in 2.10.0 version : 
Running npx playwright test --project=chromium -c uuv/playwright.config.ts  --reporter=@uuv/playwright/uuv-playwright-reporter
error: unknown command 'test'

### the output in 2.8.0 version : 
Running npx playwright test --project=chromium -c uuv/playwright.config.ts  --reporter=@uuv/playwright/uuv-playwright-reporter
Starting the run with 7 tests
  Feature: uuv\e2e\accueil.feature
    ✓ Page Accueil - Test1  (4555ms)
    ✓ Page Accueil - Test2  (2450ms)
    ✓ Page Accueil - Test3  (2440ms)
    ✓ Page Accueil - Test4 (2445ms)
    ✓ Page Accueil - Test5 (2408ms)
  Feature: uuv\e2e\test.feature
    ✓ Connexion OK  (2285ms)
    ✓ Connexion Impossible  (2257ms)
End of the tests execution
 
Test Execution Report :
  +----+-------------------------+--------+---------+--------+
  | Id | File                    | Passed | Skipped | Failed |
  +----+-------------------------+--------+---------+--------+
  | 1  | uuv\e2e\accueil.feature | 5      | 0       | 0      |
  | 2  | uuv\e2e\login.feature   | 2      | 0       | 0      |
  +----+-------------------------+--------+---------+--------+

**Comment by luifr10** [comment]
Cannot reproduce this bug
