### ISSUE TITLE
Unable to create custom step definitions - tsconfig issues

### ISSUE THREAD

**Issue by MikeDabrowski** [Orange-OpenSource/uuv#613]
**Describe the bug**
I followed the [docs](https://orange-opensource.github.io/uuv/docs/wordings/add-custom-step-definition#install-dependencies-1) but I am getting error "SyntaxError: Cannot use import statement outside a module", 
`<Unable to read "C:\Users\AHTI\IdeaProjects\uuv-test\node_modules\ts-node\src\index.ts">`

**To Reproduce**
1. Create blank npm project
2. Add playwright, uuv, ts-node as docs says
3. add custom step definitions
4. run tests - they work
5. add advanced ts-config and ts-config.e2e
6. tests no longer work

**Expected behavior**
I expected the tsconfig.e2e to be respected. It seems tests only run without tsconfig or when the config that is specified in the docs is the only config there. 

I tried keeping my adv config and putting .e2e version next to it or in uuv folder. And as soon as I remove my config tests start working.

**possible hints**
The error suggests that module resolution might be broken. And indeed - if I put ` "module": "commonjs",` in my advanced config (and remove all other tsconfigs) the tests are running. This hints that the uuv/playwright does not read the `tsconfig.e2e.json` file and defaults to baseline.

**Screenshots**
![image](https://github.com/Orange-OpenSource/uuv/assets/17836911/3abfb200-17ae-43bb-b9f3-762400d470d3)  
![image](https://github.com/Orange-OpenSource/uuv/assets/17836911/617109d5-b7c0-4f5d-bf45-04e4653510e3)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Node 21
 - uuv 2.13.1
 - intellij 2014.1.1
 - uuv plugin 1.5.0

**Additional context**
Archive with repro  
[uuv-test.zip](https://github.com/Orange-OpenSource/uuv/files/15224894/uuv-test.zip)

**Comment by luifr10** [comment]
Our bad, this part of the documentation is not up-to-date.
Your have to replace the 2 import lines by the following one :
```typescript
const { Given, When, Then } = require('@cucumber/cucumber');
const { expect } = require('@playwright/test');
```
I'll update the documentation

**Comment by luifr10** [comment]
Yes, you're right !
Here is the best solution with composite tsconfig file :
**tsconfig.json**
```json
{
    "references": [
        { "path": "./tsconfig.e2e.json" }, 
        { "path": "./tsconfig.app.json" }
    ]
}
```

**tsconfig.json**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "strict": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "lib": [
      "es2019",
      "es2018",
      "es2015",
      "dom", "ES2020.Intl"
    ],
    "plugins": [
      {
        "name": "typescript-tslint-plugin",
        "alwaysShowRuleFailuresAsWarnings": false,
        "ignoreDefinitionFiles": true
      }
    ],
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "useDefineForClassFields": false,
    "composite": true
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": false,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  },
  "allowSyntheticDefaultImports": true,
  "include": [
    "src"
  ]
}
```

**tsconfig.e2e.json**
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "composite": true,
    "outDir": "./out-tsc/app",
    "types": [
      "@uuv/playwright"
    ]
  },
  "include": [
    "uuv/cucumber/step_definitions/**/*.ts"
  ],
  "references": [
    { "path": "./tsconfig.app.json" }
  ]
}
```

**Comment by MikeDabrowski** [comment]
I found this piece. I suspect this might be just for running the tests on UUV itself but if similar pattern (not parameterised tsconfig location) is used in other places it may be the issue. I did not find any other place where ts-node config could be used...

https://github.com/Orange-OpenSource/uuv/blob/9e2d84679d8147a7c4a4d90f528bdee4958ffca3/packages/runner-cypress/test.js#L17-L24

**Comment by MikeDabrowski** [comment]
Nah this solution is not viable for us. I spend whole week trying to convert the project to use it but still keeps failing.

Latest issue is that
`Error: error TS6304: Composite projects may not disable declaration emit.`
despite `declaration: true`

We will abandon uuv for now.
