### ISSUE TITLE
Add a sentence to verify if a radio button is checked or not

### ISSUE THREAD

**Issue by valentinbertrand** [Orange-OpenSource/uuv#733]
I should see a radio named {} checked
I should see a radio named {} not checked

I should see a radio named {} checked and enabled
I should see a radio named {} checked and disabled

I should see a radio named {} not checked and enabled
I should see a radio named {} not checked and disabled

**Comment by luifr10** [comment]
The following phrases will be added for roles `radio`, `menuitemradio`, `checkbox`, `menuitemcheckbox` and  `switch` :
- I should see a(n) `roleId` named {string} checked
- I should see a(n) `roleId` named {string} unchecked

For radio role for instance :
- I should see a radio named {string} checked
- I should see a radio named {string} unchecked
