### ISSUE TITLE
[DOCUMENTATION] update title

### ISSUE THREAD

**Issue by stanlee974** [Orange-OpenSource/uuv#747]
On UUV documentation, we have title like `page title` | `brand name`.
We must have `brand name` | `page title`

**Comment by vr-varad** [comment]
hey @stanlee974 I would like to work on this issue if its open for contribution

**Comment by stanlee974** [comment]
Hey !
You're Welcome.
Thanks for your help ❤️

**Comment by vr-varad** [comment]
No problem @stanlee974  I could work on #631

**Comment by stanlee974** [comment]
@vr-varad it's a pretty cool issue. Thanks.
